### ISSUE TITLE
problems compiling to local ATLAS or mkl with gcc

### ISSUE THREAD

**Issue by TermeHansen** [ilyak/libefp#12]
I have problems getting it to compile with gcc (version 5.4.0) on Ubuntu 16.04 to local install of both ATLAS and mkl.

with ATLAS I used this in config:
```
# additional link libraries
MYLIBS= -llapack -lf77blas -latlas -lgfortran -L/mnt/batch/tasks/shared/BIGdisk/ATLAS/install/lib

# additional linker flags
MYLDFLAGS= -I/mnt/batch/tasks/shared/BIGdisk/ATLAS/install/include

# additional C flags
MYCFLAGS= -std=c99 -O3 -g -fopenmp 

# additional Fortran flags
MYFFLAGS= -g
```
and I get:
```
gcc -o efpmd -DFRAGLIB_PATH="\"/mnt/batch/tasks/shared/BIGdisk/libEFP/install/share/libefp/fraglib\"" -I../../src -I../libopt -I../libff -std=c99 -O3 -g -fopenmp  -L../../src -L../libopt -L../libff -I/mnt/batch/tasks/shared/BIGdisk/ATLAS/install/include cfg.o common.o efield.o energy.o grad.o gtest.o hess.o main.o md.o msg.o opt.o parse.o rand.o sp.o -lefp -lopt -lff -llapack -lf77blas -latlas -lgfortran -L/mnt/batch/tasks/shared/BIGdisk/ATLAS/install/lib -lm
../../src/libefp.a(clapack.o): In function `efp_dsyev':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:83: undefined reference to `dsyev_'
/mnt/batch/tasks/shared/BIGdisk/ATLAS/install/lib/liblapack.a(ATL_dgetrfC.o): In function `ATL_dgetrfC':
ATL_getrfC.c:(.text+0x11f): undefined reference to `cblas_dtrsm'

```

for mkl I tried:
```

# additional link libraries
MYLIBS=  -lgfortran -I/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/include 

# additional linker flags
mymkl=/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/
MYLDFLAGS = -Wl,--start-group {$mymkl}libmkl_gf_ilp64.a {$mymkl}libmkl_gnu_thread.a {$mymkl}libmkl_core.a -Wl,--end-group -lgomp  -lm -ldl

# additional C flags
MYCFLAGS= -std=c99 -O3 -g -fopenmp -m64

# additional Fortran flags
MYFFLAGS= -g
```

giving:
```
gcc -o efpmd -DFRAGLIB_PATH="\"/mnt/batch/tasks/shared/BIGdisk/libEFP/install/share/libefp/fraglib\"" -I../../src -I../libopt -I../libff -std=c99 -O3 -g -fopenmp -m64 -L../../src -L../libopt -L../libff -Wl,--start-group /mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_gf_ilp64.a /mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_gnu_thread.a /mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/libmkl_core.a -Wl,--end-group -lgomp  -lm -ldl cfg.o common.o efield.o energy.o grad.o gtest.o hess.o main.o md.o msg.o opt.o parse.o rand.o sp.o -lefp -lopt -lff -lgfortran -I/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/include  -lm
../../src/libefp.a(clapack.o): In function `efp_dgemm':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:69: undefined reference to `dgemm_'
../../src/libefp.a(clapack.o): In function `efp_dsyev':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:83: undefined reference to `dsyev_'
../../src/libefp.a(clapack.o): In function `efp_dgesv':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:95: undefined reference to `dgesv_'
collect2: error: ld returned 1 exit status

```

any ideas?

**Comment by ilyak** [comment]
I think you are not linking all necessary MKL libraries. Try using "-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core".

**Comment by TermeHansen** [comment]
I already have that.... writing it more like you propose would be something like:
```
# C compiler
CC= gcc

# Fortran compiler
FC= gfortran

# install prefix
PREFIX= /mnt/batch/tasks/shared/BIGdisk/libEFP/install

# fragment library path
FRAGLIB= $(PREFIX)/share/libefp/fraglib

# additional link libraries
MYLIBS=  -lgfortran -I/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/include

# additional linker flags
mymkl=/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/
MYLDFLAGS = -L${mymkl} -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lgomp -lm -ldl

# additional C flags
MYCFLAGS= -std=c99 -O3 -g -fopenmp -m64

# additional Fortran flags
MYFFLAGS= -g
```
Which still gives:
```
gcc -o efpmd -DFRAGLIB_PATH="\"/mnt/batch/tasks/shared/BIGdisk/libEFP/install/share/libefp/fraglib\"" -I../../src -I../libopt -I../libff -std=c99 -O3 -g -fopenmp -m64 -L../../src -L../libopt -L../libff -L/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/lib/intel64/ -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lgomp -lm -ldl cfg.o common.o efield.o energy.o grad.o gtest.o hess.o main.o md.o msg.o opt.o parse.o rand.o sp.o -lefp -lopt -lff -lgfortran -I/mnt/batch/tasks/shared/BIGdisk/mkl-install/compilers_and_libraries/linux/mkl/include  -lm
../../src/libefp.a(clapack.o): In function `efp_dgemm':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:69: undefined reference to `dgemm_'
../../src/libefp.a(clapack.o): In function `efp_dsyev':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:83: undefined reference to `dsyev_'
../../src/libefp.a(clapack.o): In function `efp_dgesv':
/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/src/clapack.c:95: undefined reference to `dgesv_'
collect2: error: ld returned 1 exit status
Makefile:12: recipe for target 'efpmd' failed
make[1]: *** [efpmd] Error 1
make[1]: Leaving directory '/mnt/batch/tasks/shared/BIGdisk/libEFP/libefp-1.5.0-DF/efpmd/src'
Makefile:6: recipe for target 'efpmd' failed
make: *** [efpmd] Error 2

```
